name: "Release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@magloft"
      - name: install react
        run: npm i react
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
